### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#105]
Could you review the documentation and ensure that the details of each field are correct.  In particular I believe that the Correct Article Confidence and the EPMC Licence Source fields are not up-to-date

**Comment by emanuil-tolev** [comment]
> Correct Article Confidence

This is now up to date.

> EPMC Licence Source

Ah oops. Updated version is now visible at https://compliance.cottagelabs.com/docs

I've now read through the rest of the docs and can't see any obvious errors like the EPMC licence source. I also double checked all EPMC-related columns since the docs can be quite specific about the behaviour there, but they are all up to date. I put down an extra sentence of information about how we get XML Fulltext? exactly.
