### ISSUE TITLE
Integrate eCommerce/payment portal for credit purchase

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#141]
Users will need to be able to buy credit for the system using the usual ways:

* credit/debit card
* paypal

We should also provide some instructions on paying by bank transfer on an invoice.

**Comment by markmacgillivray** [comment]
We are not implementing this now, due to changes in target market. However, I have reviewed a few options and read up on payment APIs, and if time comes to do so, I think stripe is the best option. Paypal also offers such a service, but stripe looks better documented and more integration options.

At the point where just invoicing is sufficient, we can probably best stick to doing that manually, although it is also possible to integrate with openbooks API, and it can tie in with stripe/paypal too in some ways that may be useful.

But for now, closing this.
