### ISSUE TITLE
Jobs are not always reaching completion

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#25]
A lot of jobs are appearing to get stuck around 98/99%

**Comment by richard-jones** [comment]
Several reports of this today.  Details of specific jobs by email shortly.

**Comment by richard-jones** [comment]
Actually, this one: https://lantern.cottagelabs.com/#4CamZehtSaJBuhxxD

**Comment by markmacgillivray** [comment]
Thanks, I saw the email about some issues. These are expected until I push
the changes to live, some time this week. I will update these issues when
the fixes are in.

**Comment by markmacgillivray** [comment]
This has been done on dev and tested with stuck jobs for wellcome processing, all of which now clear successfully. Will move code over to live and see if it clears the lantern ones too.

**Comment by markmacgillivray** [comment]
This issue is also in the wellcome milestone... bit confused as to what those milestones mean! Anyway it doesn't matter, just working through them.

**Comment by emanuil-tolev** [comment]
This continues to be an issue on live. Processes can be cleared via calling /reset, but that can't be done regularly. We need some sort of solution where sheets don't need manual intervention to reach 100%. This can be via resetting processes which appear to have stayed running for too long, or any other way which achieves the goal of avoiding sheets being (and appearing to be) stuck at less than 100% completion.

It's fairly high priority, since it's seen as an expected feature of the move to a new version of the compliance app. The old Python one got stuck as well (for very different reasons) and this old problem was one of the reasons to go ahead with the refactor, alongside the new feature developments.

**Comment by emanuil-tolev** [comment]
This continues to be an issue on live. Processes can be cleared via calling /reset, but that can't be done regularly. We need some sort of solution where sheets don't need manual intervention to reach 100%. This can be via resetting processes which appear to have stayed running for too long, or any other way which achieves the goal of avoiding sheets being (and appearing to be) stuck at less than 100% completion.

It's fairly high priority, since it's seen as an expected feature of the move to a new version of the compliance app. The old Python one got stuck as well (for very different reasons) and this old problem was one of the reasons to go ahead with the refactor, alongside the new feature developments.

**Comment by markmacgillivray** [comment]
Stuck processes for at least the last three months have only been due to
actual errors in how we handle things, rather than bottlenecks or bad
system design. So as discussed last time, I don't think we should
automatically clear stuck processes - they are highly likely just to stick
again. I proposed adding a regular check to see if certain processes were
sticking, and to send an email alert when they are. I used to check
manually, but now the alert would be useful. Unless some new reason has
come up to change this plan, then can I stick to doing what i had intended?
And if this needs more urgency, then by when should it be done, and in
place of what, regarding current milestones? Probably something to discuss
at the weekend.
On 13 Jul 2016 10:06, "Emanuil Tolev" notifications@github.com wrote:

This continues to be an issue on live. Processes can be cleared via calling
/reset, but that can't be done regularly. We need some sort of solution
where sheets don't need manual intervention to reach 100%. This can be via
resetting processes which appear to have stayed running for too long, or
any other way which achieves the goal of avoiding sheets being (and
appearing to be) stuck at less than 100% completion.

It's fairly high priority, since it's seen as an expected feature of the
move to a new version of the compliance app. The old Python one got stuck
as well (for very different reasons) and this old problem was one of the
reasons to go ahead with the refactor, alongside the new feature
developments.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
https://github.com/CottageLabs/LanternPM/issues/25#issuecomment-232299646,
or mute the thread
https://github.com/notifications/unsubscribe/AAuXCIkEiqKMz2NgPQzSrWE28Yszdzl7ks5qVKqmgaJpZM4Inwbb
.

**Comment by emanuil-tolev** [comment]
> Stuck processes for at least the last three months have only been due to actual errors in how we handle things, rather than bottlenecks or bad system design. So as discussed last time, I don't think we should automatically clear stuck processes - they are highly likely just to stick again.

Ah right. However, so far I've observed that when I reset processes the stuck sheets always complete successfully. This probably means the unhandled exceptions causing the processes to crash in the first place are intermittent, e.g. perhaps third parties returning 500-s that we don't yet handle.

I agree we need to use the information on such exceptions to improve our code. I think we can get this from simply looking at app's logs. I suppose we could even log the output of the Lantern cron job responsible for running the `.process` function to a separate file, and look at this. We can even have the system alert us when it experiences such an error, either via some kind of general exception handling (if possible in meteor) or just by running a simple job that looks for errors in the app logs and emails us.

Ultimately I think if it is possible to retry a process, we should. So far in the 10+ cases I've had to do it (first on the test site, and now on live), it has always resulted in the affected sheets completing successfully, so it does appear to bring some non-trivial improvement.

Stuck sheets make the tool appear quite unreliable, both to Lantern and to Wellcome users. The latter have had to deal with this kind of problem for many months now (mostly in the old, and now in the new compliance app).

**Comment by markmacgillivray** [comment]
If we automatically unstick them because of time outs from external
sources, then we won't know when those are occurring. Yes we can look at
logs, but that is a separate issue. The logs are queryable via mupx
already, but could be stored differently, in very many different ways. What
would be most useful in determining what would suit best for that is a
testing system for the api, which we still don't have yet. So that's
discussion for the weekend too - who is actually going to build one?
Perhaps Richard has time over the summer.

For the current issue, before having tests and appropriate logging, we can
automatically unstick processes and only email if they remain stuck. I'd
still prefer to do this using the method I'd originally intended though.
Also, I didn't know we even had a wellcome milestone to continue working on
- I thought we'd already agreed successful delivery to them, and the
  milestone was just out of date. We seem to have miscommunication here.

**Comment by emanuil-tolev** [comment]
Yeah, I thought we were finished as well, but unfortunately not if there are still issues affecting quality to this extent. Hopefully there won't be any more past what's now in the milestone.

**Comment by emanuil-tolev** [comment]
I'm happy to go with email alert when a stuck process is detected. I think unsticking it just once before sending the alert is potentially a good idea. If you send the alerts to lantern@ or to you and me, and if I know how to fix an alerted problem, I'll make PRs.

**Comment by markmacgillivray** [comment]
Batch1-3.csv (of which there are multiple copies) and Batch10-12.csv are the only jobs not complete that have more than zero processes.

Add a catch to the system to set jobs with zero processes to done straight away - this will relate to the upload problem from IE. 

For the above jobs which are batch jobs from Brunel, these may be due to the already fixed (but not yet deployed to live) epmc missing data issue, so will test those after push and processes reset.

**Comment by markmacgillivray** [comment]
Only jobs that did not finish were suffering from an error with epmc not returning any data object at all, so that now gets caught. Remaining ones were suffering from the IE upload issue - they had no processes, so never got checked for completion either. Empty jobs can still be submitted, but automatically get set to done now. Also, every 30 minutes the system now checks the processes running, and if the list is the same as 30 minutes ago it emails me (once I check this, I will have it email sysadmin).

**Comment by emanuil-tolev** [comment]
Wellcome reported https://compliance.cottagelabs.com/#WaXwS86Bw8mJiHXvS as being stuck on 99.9%, having been uploaded yesterday afternoon (presumably after I updated them on our newest fixes). EDIT: it was reported stuck today at 11:41 AM, so > 16 hours after upload. You got no message about any errors.

It is 100% now - I've not run a reset myself.

When I was planning a fix (before the July CL getaway) I simply wrote cause_error inside the processing part of the lantern service in the API. It worked quite well, everything I uploaded was "stuck" on 0% and I could see the crashes in the log. If you test the new email on error locally and it works, that's probably sufficient evidence that it works OK to then start sending the alerts to sysadmin@cottagelabs.com so either of us can look at them and pick them up.

**Comment by markmacgillivray** [comment]
Error messaging checked and working.

**Comment by markmacgillivray** [comment]
Stuck processes error messaging now goes to sysadmin@cottagelabs.com and has been tested with actual errors - today eupmc was down so I took advantage of that. I also added a link to the msg to the reset processes endpoint. If you want to trigger alerts based on the incoming email in gmail, the subject line starts with "CL ALERT" and I will use that as convention for any future email alerts we build into the API.
