### ISSUE TITLE
Scale testing

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#39]
Given how quickly we had to scale at the start of the project, it is worth doing some dedicated scale testing of our own.  Spin up a few more machines, feed a load of test data into the system, and see how it fares.  May be useful to mock-out the external endpoints so that they can be made to behave in odd ways (like, timing out, etc), so we can be sure we can handle that.

Allocating this to Before OR milestone, though actually this is likely to be much longer-term work, but it would be good to have done some scale testing before we open it up to all the participants there.

**Comment by markmacgillivray** [comment]
Unlikely to get this sufficiently done by next week, but system has been in use by 4 real and 6 dev users, submitting 32 jobs and collecting over 14000 results, no problem. Can definitely turn on some extra machines for next week though, just in case. Monitoring is already installed on them too, so any load peaks will trigger warnings (we have had no load peak warnings since moving to the cluster model).

**Comment by richard-jones** [comment]
It sounds like the way we scaled up worked well, even if we didn't get the usage to fully test it.  Should we leave this open, to remind us to do a full scale test at some point, or can we close it off?

**Comment by markmacgillivray** [comment]
Will close for now. When we build a testing mechanism more fully, we can reconsider scale testing in that context
