### ISSUE TITLE
Make wellcome UI live

### ISSUE THREAD

**Issue by emanuil-tolev** [CottageLabs/LanternPM#63]
If we could point a wellcome UI to the live lantern API that would be good.

Concerns remaining over sign-off are now small enough that we can deploy the project live. There are some cosmetic things (docs etc.) that I will do. @markmacgillivray @richard-jones you'll probably be happy to hear this :).

There is one other concern: the old python system queued jobs. In the new one the following behaviour was observed on the dev API:
1. upload a big sheet. It ticks along.
2. upload a smaller sheet. Sheet # 1 stops in its tracks.
3. Sheet 2 finishes.
4. Sheet 1 resumes ticking along.
5. Upload another (big or small) sheet.
6. Sheet 1 stops again until Sheet 3 has finished.

I presume this is to some degree a function of the fact that the dev API only runs on 1 machine (right?). So in a live environment queuing will matter less since speed will be improved.

**Comment by markmacgillivray** [comment]
Ready.

**Comment by emanuil-tolev** [comment]
OK - is 178.62.93.81 (your test machine) serving the UIs? To point the domain to it.

**Comment by markmacgillivray** [comment]
Yep.

**Comment by emanuil-tolev** [comment]
OK, will repoint it tomorrow if you'd like to talk first.

**Comment by markmacgillivray** [comment]
We don't have to talk first, was just suggesting in case you want to go
over anything

**Comment by emanuil-tolev** [comment]
OK, I've pointed compliance.cottagelabs.com to that IP. Tried it first locally (/etc/hosts override) and it works beautifully. I'm curious to see what the performance is - really don't fancy having to somehow prioritise jobs because later ones interrupt the processing of earlier ones.. But I'll let Cecy have a go.

**Comment by markmacgillivray** [comment]
Yes at the moment processes are in order of how recent they were submitted. We did discuss adding some sort of priority method, but have not decided on what it should be yet. We considered adding a weighting to large jobs so that small ones are prioritised, and then running jobs in order they were received, not the order of which is most recent. That is possible - it won't be hard to add prioritisation, we just need to decide how we want it. Another option could be prioritising certain user groups. We could also have more machines processing more jobs for certain user groups - there is quite a range of options!

The current setting works pretty well because if people upload a big job they are less likely to be sitting around watching the UI and waiting for it, so then if someone throws in a small job and sits there waiting for it, they will get it back very fast. Even if lots of small jobs come in, people should see a bit of progress, but then some delay while other jobs take priority. The big job will sit for possibly quite a while not getting done, but then chances are people won't check that big job again until they get the email or until the next day.

We could easily add a regular check to see how many outstanding jobs we have over time, and when that hits a certain threshold, throw a warning email and we turn on extra machines. Like you mention, as long as we have enough processing power the order does not matter too much - we just need to do stuff fast enough to keep people happy.

**Comment by emanuil-tolev** [comment]
Excellent, good to know we have quite a lot of flexibility!

I thought of something else .. the occasional stuck process. Wonder if we should occasionally (no more often than every 30 min) send GET to /processes/reset?

**Comment by markmacgillivray** [comment]
No we shouldn't. But a more intelligent check of that endpoint and a list
of the processes running, when it seems to stall, may be worth doing
