### ISSUE TITLE
Ability to delete account

### ISSUE THREAD

**Issue by richard-jones** [CottageLabs/LanternPM#68]
Since we allow for terms and conditions of usage to change, and that includes the terms associated with having an account, we should have a clear way for someone to remove their account from the system

**Comment by markmacgillivray** [comment]
We may actually have to alter the T&Cs here rather than offering to delete accounts. As accounts consist of nothing more than the email address the user logs in with, if they were to delete an account and then try logging in again, they would immediately be allowed to do so. The only thing I could actually delete in an account deletion would be the jobs they previously submitted. We do store their email address of course in their account, so I could delete that too - but it would not actually seem any different if they were to try to login again.

So, do we want to delete previous jobs when a user selects to delete account? - It may seem that the obvious answer is yes, but given that we are also configuring jobs as result pages with URLs that we expect/hope people to share, it is going to seem pretty odd if other users go back to a job result set they previously found useful, only to find it does not exist any more, for no apparent reason.

This is probably something we could not have for the beta launch anyway, and can quickly add it any time we decide the answer to this question.
